# Generated by Django 5.1.6 on 2025-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(default='Basic Visit', max_length=50)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact_person_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
